import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Blog - Contatti",
  description: "Generated by create next app",
};

const Page = () => {
  return <h1>Contatti</h1>;
};

export default Page;
